### ISSUE TITLE
Automated Testing using Selenium

### ISSUE THREAD

**Issue by blobbered** [recurly/recurly-js-examples#29]
Because implementing recurly.js creates iframes in our form, automated testing with selenium requires switching of frames (e.g., `driver.switch_to.frame(frame_element)`). However, even after switching to the requisite recurly iframe, I still cannot seem to select the text field element. This problem might be related to [this issue](https://github.com/SeleniumHQ/selenium/issues/2596), but regardless any suggestions (or an example) would be appreciated.

**Comment by chrissrogers** [comment]
Apologies for not seeing your issue sooner! While this is quite stale now, I'll provide an answer in case others are wondering the same.

Since that restriction is a direct consequence of security and PCI requirements inherent to Recurly.js (Selenium being unable to access the field is equivalent to any other client side script being unable to access the field), my best suggestion for testing would be to stub the field's behavior in your tests. You can do so using any javascript stubbing framework, but I suggest [Sinon](https://sinonjs.org/)
